### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by gabitoesmiapodo** [BootNodeDev/dAppBooster#115]
There's a lot to do: components docs, readme polishing, etc.

Maybe we can use the wiki https://github.com/BootNodeDev/db-ui-toolkit/wiki

Some examples:

https://github.com/ohmyzsh/ohmyzsh/wiki
https://github.com/ChimeraOS/chimeraos/wiki
https://github.com/opencv/opencv/wiki
https://github.com/golang/go/wiki
https://github.com/scikit-learn/scikit-learn/wiki

**Comment by fernandomg** [comment]
https://vocs.dev/
