### ISSUE TITLE
npx dappboster

### ISSUE THREAD

**Issue by nicosampler** [BootNodeDev/dAppBooster#237]
After testing out `npx dappboster` I think we could do the following modifications. Please, if you find the following suggestions are not necessary just close the issue. 

1. Allow defining the folder name where the dappboster code will be located, for example `npx dappbooster myNyDapp`.

2. The following is not something I am convinced of, but is the common practice to keep pointing to the dappboster repository? Most of the time users will want to manage their repo, so perhaps we can: 
    * clone
    * Remove Git
    * cp .env.example to .env. 
    * `pnpm install`
    
3. we could suggest to run:
    * `git init`
    * `git remote add dappbooster git@github.com:BootNodeDev/dAppBooster.git`

**Comment by fernandomg** [comment]
@nicosampler as this is not part of the repo, I'll let you know of this task progress here...

I addressed all the suggestions (I guess)

you can see the result in the following video:

https://github.com/user-attachments/assets/7e6b1246-5a0e-45bb-ac61-cc9a8653dfb0

The only difference is that aside from removing the .git dir, it also runs `git init`, so the user can do an initial commit with whatever they want.

Let me know if it works well for you

**Comment by gabitoesmiapodo** [comment]
What's the repo for this script? 

We should add it to the project's repos if there's one.

**Comment by fernandomg** [comment]
> What's the repo for this script?
> 
> We should add it to the project's repos if there's one.

there's no repo, it was just a personal tiny project to automate the project setup. Maybe we can move it to a new project when we work on #243

**Comment by fernandomg** [comment]
https://github.com/fernandomg/dAB-cloner

**Comment by gabitoesmiapodo** [comment]
Cool.

We use [pnpm](https://pnpm.io/), so `pnpm dlx` would be more adequate I guess.

**Comment by gabitoesmiapodo** [comment]
Adding

```
cp .env.example .env.local
```

and

```
pnpm i
```

to the script would be nice (or make it optional maybe?).

Can we move this to a company owned repo, or has it to be an individual's repo?

**Comment by fernandomg** [comment]
I'll move it to the org, not sure about making the other steps.

Although, they can be easily added. Will give it a try

**Comment by fernandomg** [comment]
@gabitoesmiapodo https://github.com/BootNodeDev/dAppBooster-starter 👀

**Comment by gabitoesmiapodo** [comment]
Nice.

We should add this to dAppBooster's readme. My only concern is that there's some divergence regarding the steps in the readme (copying `.env.example` to `.env.local` and running `pnpm i` are missing here, for example).

Somebody might run `pnpx dappbooster my-project` and miss those because they thought that they were already executed.

Maybe we can address that by adding a final note "Remember to do so and so..."

**Comment by fernandomg** [comment]
closing this, with the following final version:
<img width="503" alt="image" src="https://github.com/user-attachments/assets/e55cb7e9-07a3-4426-ac7d-76d17cf34890">
