### ISSUE TITLE
TokenInput crashes

### ISSUE THREAD

**Issue by gabitoesmiapodo** [BootNodeDev/dAppBooster#293]
**Describe the bug**

TokenInput crashes.

**To Reproduce**

Enter a number several characters long and it crashes.

**Expected behavior**

It shouldn't crash.

**Screenshots**

![yay](https://github.com/user-attachments/assets/c7bed723-fb8a-4afb-a815-e383ab35ff0e)

**Additional context**

Tested on https://dappbooster.dev/ and also on a local copy of this repository.

**Comment by fernandomg** [comment]
The problem has to do with the formatter, it's adding the `,` to separate thousands.

After that was solved, two new problems were raised; when clicking `max` the value loaded to the input is not formatted nor validated.


https://github.com/user-attachments/assets/2a91e766-9d07-4bf4-a39f-af2493a52719
